# Generated by Django 5.1 on 2024-12-01 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.ForeignKey(db_column='Barcode', on_delete=django.db.models.deletion.CASCADE, related_name='gruppen_as_barcode', to='customermanagementapp.barcodeelement')),
                ('gruppen_barcode', models.ForeignKey(db_column='GruppenBarcode', on_delete=django.db.models.deletion.CASCADE, related_name='gruppen_as_gruppenbarcode', to='customermanagementapp.barcodeelement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gruppen_barcode', 'barcode'), name='unique_gruppen_relation')],
            },
        ),
    ]
