# Generated by Django 5.1 on 2024-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicemanagerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hersteller_view',
            fields=[
                ('herstellerid', models.IntegerField(db_column='HerstellerID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Hersteller',
                'managed': False,
            },
        ),
    ]
