# Generated by Django 5.1 on 2024-12-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicemanagerapp', '0003_gruppe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruppe',
            options={'managed': False},
        ),
    ]
