# Generated by Django 5.1 on 2024-12-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicemanagerapp', '0004_alter_gruppe_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gruppe',
            table='Gruppen',
        ),
    ]
