# Generated by Django 5.1 on 2024-12-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicemanagerapp', '0005_alter_gruppe_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruppe',
            options={},
        ),
    ]
