# Generated by Django 5.1 on 2024-12-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicemanagerapp', '0006_alter_gruppe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruppe',
            options={'managed': False},
        ),
    ]
