name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  if: contains(github.event.head_commit.message, 'build_lvsw') # Place 'if' at step level
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        if: contains(github.event.head_commit.message, 'build_lvsw') # Place 'if' at step level
        uses: actions/checkout@v3

      - name: Login to DockerHub
        if: contains(github.event.head_commit.message, 'build_lvsw') # Place 'if' at step level
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: contains(github.event.head_commit.message, 'build_lvsw') # Place 'if' at step level
        uses: docker/build-push-action@v3
        with:
          context: .
          file: LVSW/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lvsw:latest
          build-args: >
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
